[workspace]

members = [ 
    "src/deque", "src/hash_map", 
    "src/linked_list", 
    "src/queue", 
    "src/recursion", 
    "src/searching", "src/sorting", 
    "src/stack", "src/tree", 
    "src/vec",
]
