[package]
name = "practices"
version = "0.1.0"
edition = "2021"

[dependencies]
vec = { path = "../vec" }
hash_map = { path = "../hash_map" }
chrono = "0.4"
sha2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
hex = "0.4"